import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * El esquema completo: dieciocho tablas, sus índices y sus restricciones.
 *
 * Deja la base lista para operar desde cero. Cada cambio posterior del esquema va
 * en su propia migración.
 */
export class Baseline1786211523200 implements MigrationInterface {
    name = 'Baseline1786211523200'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "ml_user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" character varying NOT NULL, "mlUserId" character varying NOT NULL, "nickname" character varying, "email" character varying, "fullName" character varying, "accessToken" character varying NOT NULL, "refreshToken" character varying NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "ordersSyncedUntil" TIMESTAMP WITH TIME ZONE, "disconnectedAt" TIMESTAMP WITH TIME ZONE, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3f6b8e524b6e0c0c1c7864d021e" UNIQUE ("userId"), CONSTRAINT "UQ_056a194b9f0ed2e2653f61f895c" UNIQUE ("mlUserId"), CONSTRAINT "PK_69fd073969cc1f0d00ac185b536" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "picture" ("id" character varying NOT NULL, "secureUrl" character varying NOT NULL, CONSTRAINT "PK_31ccf37c74bae202e771c0c2a38" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attribute" ("id" character varying NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_b13fb7c5c9e9dff62b60e0de729" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attribute_option_detailed" ("id" SERIAL NOT NULL, "number" double precision NOT NULL, "unit" character varying NOT NULL, "attributeId" character varying NOT NULL, CONSTRAINT "UQ_80c968aa65a3e2701cc062f60d9" UNIQUE ("number", "unit", "attributeId"), CONSTRAINT "PK_08683880a7804c1235f0801c315" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_80c968aa65a3e2701cc062f60d" ON "attribute_option_detailed" ("number", "unit", "attributeId") `);
        await queryRunner.query(`CREATE TABLE "attribute_option" ("id" SERIAL NOT NULL, "mlId" character varying, "valueName" character varying NOT NULL, "attributeId" character varying, "detailedId" integer, CONSTRAINT "UQ_b6cba9a12eff2359c1efda994ad" UNIQUE ("attributeId", "valueName"), CONSTRAINT "REL_e3c11e0a8635a34ec98815e0f7" UNIQUE ("detailedId"), CONSTRAINT "PK_06630b72345d91a8e3cb5245a57" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b6cba9a12eff2359c1efda994a" ON "attribute_option" ("attributeId", "valueName") `);
        await queryRunner.query(`CREATE TABLE "variation" ("id" bigint NOT NULL, "price" numeric(12,2) NOT NULL, "availableQuantity" integer NOT NULL, "soldQuantity" integer NOT NULL, "itemId" character varying, CONSTRAINT "PK_739a8640e52a196d9df6a31211a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "item" ("id" character varying NOT NULL, "title" character varying NOT NULL, "categoryId" character varying NOT NULL, "price" numeric(12,2) NOT NULL, "currencyId" character varying NOT NULL, "initialQuantity" integer NOT NULL, "availableQuantity" integer NOT NULL, "soldQuantity" integer NOT NULL, "status" character varying NOT NULL, "health" double precision, "logisticType" character varying NOT NULL, "permalink" character varying NOT NULL, "thumbnail" character varying NOT NULL, "dateCreated" TIMESTAMP NOT NULL DEFAULT now(), "lastUpdated" TIMESTAMP NOT NULL DEFAULT now(), "startTime" TIMESTAMP NOT NULL, "stopTime" TIMESTAMP NOT NULL, "expirationTime" TIMESTAMP NOT NULL, "mlUserId" uuid NOT NULL, CONSTRAINT "PK_d3c0c71f23e7adcf952a1d13423" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_97561f4b60bd81ff26a46c8ad8" ON "item" ("mlUserId") `);
        await queryRunner.query(`CREATE TYPE "public"."order_item_type_enum" AS ENUM('item', 'variation')`);
        await queryRunner.query(`CREATE TABLE "order_item" ("id" SERIAL NOT NULL, "type" "public"."order_item_type_enum" NOT NULL, "mlItemId" character varying NOT NULL, "mlVariationId" bigint, "title" character varying NOT NULL, "quantity" integer NOT NULL, "unitPrice" numeric(12,2) NOT NULL, "saleFee" numeric(12,2) NOT NULL, "currencyId" character varying NOT NULL, "baseExchangeRate" numeric(18,6), "baseCurrencyId" character varying, "orderId" bigint NOT NULL, "itemId" character varying, "variationId" bigint, CONSTRAINT "PK_d01158fe15b1ead5c26fd7f4e90" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_646bf9ece6f45dbe41c203e06e" ON "order_item" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_31d565f22a96ba2d4b2f70f723" ON "order_item" ("mlItemId") `);
        await queryRunner.query(`CREATE INDEX "IDX_628e853a1433b1288c375dfcb9" ON "order_item" ("mlVariationId") `);
        await queryRunner.query(`CREATE TABLE "order" ("id" bigint NOT NULL, "status" character varying NOT NULL, "dateCreated" TIMESTAMP WITH TIME ZONE NOT NULL, "dateClosed" TIMESTAMP WITH TIME ZONE, "dateLastUpdated" TIMESTAMP WITH TIME ZONE NOT NULL, "totalAmount" numeric(12,2) NOT NULL, "paidAmount" numeric(12,2), "currencyId" character varying NOT NULL, "shippingCost" numeric(12,2), "couponAmount" numeric(12,2) NOT NULL DEFAULT '0', "packId" bigint, "buyerNickname" character varying, "mlUserId" uuid NOT NULL, "shipmentId" bigint, CONSTRAINT "PK_1031171c13130102495201e3e20" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b1f6e7a2d5478991c1e245a4b4" ON "order" ("mlUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ca0148aa1a5929e2a7a1f11f60" ON "order" ("dateCreated") `);
        await queryRunner.query(`CREATE INDEX "IDX_5b24586a2663f7f23e3257be62" ON "order" ("dateLastUpdated") `);
        await queryRunner.query(`CREATE INDEX "IDX_af77cc522fdf7b440f0dc1077a" ON "order" ("packId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b706d170f54c48fbcd315a9eaf" ON "order" ("shipmentId") `);
        await queryRunner.query(`CREATE TABLE "shipment" ("id" bigint NOT NULL, "packId" bigint, "status" character varying, "substatus" character varying, "logisticMode" character varying, "logisticType" character varying, "senderCost" numeric(12,2), "receiverCost" numeric(12,2), "senderDiscount" numeric(12,2), "grossAmount" numeric(12,2), "trackingNumber" character varying, "trackingMethod" character varying, "declaredValue" numeric(12,2), "dateCreated" TIMESTAMP WITH TIME ZONE, "lastUpdated" TIMESTAMP WITH TIME ZONE, "mlUserId" uuid NOT NULL, CONSTRAINT "PK_f51f635db95c534ca206bf7a0a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fc82561370970a7d7683eafde0" ON "shipment" ("mlUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1259987790af9fd7eefa8b8cee" ON "shipment" ("packId") `);
        await queryRunner.query(`CREATE TABLE "sku_equivalence" ("id" SERIAL NOT NULL, "fromItemId" character varying NOT NULL, "fromVariationId" bigint, "toItemId" character varying NOT NULL, "toVariationId" bigint, "reason" character varying, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "mlUserId" uuid NOT NULL, CONSTRAINT "UQ_sku_equivalence_origen" UNIQUE ("mlUserId", "fromItemId", "fromVariationId"), CONSTRAINT "PK_c69165ba2ac4e88947a7771e7b5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0c6b1de474ec582a0ba4824fe3" ON "sku_equivalence" ("mlUserId") `);
        await queryRunner.query(`CREATE TABLE "additional_cost_type" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "mlUserId" uuid NOT NULL, CONSTRAINT "UQ_8c8245d6a6ee9a2130f6db182ba" UNIQUE ("mlUserId", "name"), CONSTRAINT "PK_842a84cf6ad93229f88cdf76353" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_541399443980f2e0b65cf41f43" ON "additional_cost_type" ("mlUserId") `);
        await queryRunner.query(`CREATE TYPE "public"."additional_cost_kind_enum" AS ENUM('fixed', 'percentage')`);
        await queryRunner.query(`CREATE TABLE "additional_cost" ("id" SERIAL NOT NULL, "kind" "public"."additional_cost_kind_enum" NOT NULL, "amount" numeric(12,2) NOT NULL, "currency" character varying, "exchangeToUYURate" numeric(10,4), "paidAt" TIMESTAMP WITH TIME ZONE, "importationId" integer NOT NULL, "typeId" integer NOT NULL, CONSTRAINT "PK_f033fe8ecc3dcb1c2e5709f2ffc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_07a14ae0d72cf1b421928e32d3" ON "additional_cost" ("importationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_864571f3c5ef4e22e76b4cba25" ON "additional_cost" ("typeId") `);
        await queryRunner.query(`CREATE TABLE "importation" ("id" SERIAL NOT NULL, "orderDate" TIMESTAMP NOT NULL, "arrivalDate" TIMESTAMP NOT NULL, "expectedNetUYU" numeric(14,2) NOT NULL DEFAULT '0', "mlUserId" uuid NOT NULL, CONSTRAINT "PK_7911da5f541dc3436c478d11bcd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3ff2ada593b35db92a146a818a" ON "importation" ("mlUserId") `);
        await queryRunner.query(`CREATE TYPE "public"."adjustment_type_enum" AS ENUM('destruction', 'mutation', 'swap')`);
        await queryRunner.query(`CREATE TABLE "adjustment" ("id" SERIAL NOT NULL, "type" "public"."adjustment_type_enum" NOT NULL, "reason" text NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "occurredAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "mlUserId" uuid NOT NULL, "importationProductId" integer, "orderItemId" integer, "targetItemId" character varying, "targetVariationId" bigint, CONSTRAINT "CHK_adjustment_source" CHECK (("importationProductId" IS NOT NULL)::int + ("orderItemId" IS NOT NULL)::int = 1), CONSTRAINT "PK_f84d8d269b59850fb017ee1630b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6a441d0c6ebb95ebeee687e7d3" ON "adjustment" ("mlUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ef8cb4525a57f8cd4259d05bd7" ON "adjustment" ("importationProductId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b860d19aac2598cd33a2d77143" ON "adjustment" ("orderItemId") `);
        await queryRunner.query(`CREATE TABLE "importation_product" ("id" SERIAL NOT NULL, "quantity" integer NOT NULL, "quantitySold" integer NOT NULL DEFAULT '0', "quantityAdjusted" integer NOT NULL DEFAULT '0', "price" numeric(12,2) NOT NULL, "expectedUnitPriceUYU" numeric(12,2), "currency" character varying NOT NULL, "exchangeToUYURate" numeric(10,4) NOT NULL, "generatedById" integer, "importationId" integer, "itemId" character varying, "variationId" bigint, CONSTRAINT "CHK_importation_product_item_xor_variation" CHECK (("itemId" IS NOT NULL)::int + ("variationId" IS NOT NULL)::int = 1), CONSTRAINT "PK_f24187d5d812e0d19c47b83685e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_94481838aa4fdee933e806b3cb" ON "importation_product" ("generatedById") `);
        await queryRunner.query(`CREATE TYPE "public"."sale_allocation_source_enum" AS ENUM('order', 'historical')`);
        await queryRunner.query(`CREATE TABLE "sale_allocation" ("id" SERIAL NOT NULL, "source" "public"."sale_allocation_source_enum" NOT NULL DEFAULT 'order', "mlItemId" character varying NOT NULL, "mlVariationId" bigint, "quantity" integer NOT NULL, "soldAt" TIMESTAMP WITH TIME ZONE NOT NULL, "mlUserId" uuid NOT NULL, "orderItemId" integer, "importationProductId" integer NOT NULL, CONSTRAINT "PK_6bd4d5f5899d4fdf8cccbcb2555" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_654d57c65cfd091f1a1c7fcbb3" ON "sale_allocation" ("mlUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_77d70782a1bb8973f3f1ca9bb3" ON "sale_allocation" ("orderItemId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bcab61e68fed299847357b5ed6" ON "sale_allocation" ("mlItemId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a32788fc15e944d3b66b3a1b20" ON "sale_allocation" ("importationProductId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9617829e678bb9cdb844c86f73" ON "sale_allocation" ("soldAt") `);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "variation_attribute_options" ("variationId" bigint NOT NULL, "attributeOptionId" integer NOT NULL, CONSTRAINT "PK_79ea16361676658a373a0697665" PRIMARY KEY ("variationId", "attributeOptionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d29cb7a5f217c9e300c41b5f5d" ON "variation_attribute_options" ("variationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0a1f619c76288c49c0a92f974b" ON "variation_attribute_options" ("attributeOptionId") `);
        await queryRunner.query(`CREATE TABLE "variation_pictures" ("variationId" bigint NOT NULL, "pictureId" character varying NOT NULL, CONSTRAINT "PK_bfb0b164201707761e0fc058277" PRIMARY KEY ("variationId", "pictureId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e952b37a42a238b4adb17d6e35" ON "variation_pictures" ("variationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c9fee9e9929ee0f136606f4958" ON "variation_pictures" ("pictureId") `);
        await queryRunner.query(`CREATE TABLE "item_pictures" ("itemId" character varying NOT NULL, "pictureId" character varying NOT NULL, CONSTRAINT "PK_e7bdccc20df833596777080fe29" PRIMARY KEY ("itemId", "pictureId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_72db30236d484d45d583ba187a" ON "item_pictures" ("itemId") `);
        await queryRunner.query(`CREATE INDEX "IDX_df9bf4e0e22ec4c690c8ecdd6c" ON "item_pictures" ("pictureId") `);
        await queryRunner.query(`CREATE TABLE "item_attributes" ("itemId" character varying NOT NULL, "attributeId" character varying NOT NULL, CONSTRAINT "PK_761478c462de51a52b3621d5e53" PRIMARY KEY ("itemId", "attributeId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d2f52db45e62d7dec5e7a9de23" ON "item_attributes" ("itemId") `);
        await queryRunner.query(`CREATE INDEX "IDX_19bef966888dbf33b1ce5d6328" ON "item_attributes" ("attributeId") `);
        await queryRunner.query(`CREATE TABLE "item_attribute_options" ("itemId" character varying NOT NULL, "attributeOptionId" integer NOT NULL, CONSTRAINT "PK_b994e729771692be1dd3811ec40" PRIMARY KEY ("itemId", "attributeOptionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b97c87796847389df04aad724a" ON "item_attribute_options" ("itemId") `);
        await queryRunner.query(`CREATE INDEX "IDX_99d555bf4d5719fd6c0b602cfe" ON "item_attribute_options" ("attributeOptionId") `);
        await queryRunner.query(`ALTER TABLE "attribute_option" ADD CONSTRAINT "FK_0f970f7e5632357537ae1230ea8" FOREIGN KEY ("attributeId") REFERENCES "attribute"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attribute_option" ADD CONSTRAINT "FK_e3c11e0a8635a34ec98815e0f76" FOREIGN KEY ("detailedId") REFERENCES "attribute_option_detailed"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "variation" ADD CONSTRAINT "FK_cff7ea1877724ac753027c2a72a" FOREIGN KEY ("itemId") REFERENCES "item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item" ADD CONSTRAINT "FK_97561f4b60bd81ff26a46c8ad83" FOREIGN KEY ("mlUserId") REFERENCES "ml_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_646bf9ece6f45dbe41c203e06e0" FOREIGN KEY ("orderId") REFERENCES "order"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_e03f3ed4dab80a3bf3eca50babc" FOREIGN KEY ("itemId") REFERENCES "item"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_e000525ee0adaa7774b12a198ba" FOREIGN KEY ("variationId") REFERENCES "variation"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_b1f6e7a2d5478991c1e245a4b48" FOREIGN KEY ("mlUserId") REFERENCES "ml_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order" ADD CONSTRAINT "FK_b706d170f54c48fbcd315a9eaf3" FOREIGN KEY ("shipmentId") REFERENCES "shipment"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipment" ADD CONSTRAINT "FK_fc82561370970a7d7683eafde04" FOREIGN KEY ("mlUserId") REFERENCES "ml_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sku_equivalence" ADD CONSTRAINT "FK_0c6b1de474ec582a0ba4824fe31" FOREIGN KEY ("mlUserId") REFERENCES "ml_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "additional_cost_type" ADD CONSTRAINT "FK_541399443980f2e0b65cf41f430" FOREIGN KEY ("mlUserId") REFERENCES "ml_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "additional_cost" ADD CONSTRAINT "FK_07a14ae0d72cf1b421928e32d3e" FOREIGN KEY ("importationId") REFERENCES "importation"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "additional_cost" ADD CONSTRAINT "FK_864571f3c5ef4e22e76b4cba25e" FOREIGN KEY ("typeId") REFERENCES "additional_cost_type"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "importation" ADD CONSTRAINT "FK_3ff2ada593b35db92a146a818a0" FOREIGN KEY ("mlUserId") REFERENCES "ml_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adjustment" ADD CONSTRAINT "FK_6a441d0c6ebb95ebeee687e7d36" FOREIGN KEY ("mlUserId") REFERENCES "ml_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adjustment" ADD CONSTRAINT "FK_ef8cb4525a57f8cd4259d05bd74" FOREIGN KEY ("importationProductId") REFERENCES "importation_product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adjustment" ADD CONSTRAINT "FK_b860d19aac2598cd33a2d77143a" FOREIGN KEY ("orderItemId") REFERENCES "order_item"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adjustment" ADD CONSTRAINT "FK_acf7b6bb7b1893d4aeed2cea6a3" FOREIGN KEY ("targetItemId") REFERENCES "item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "adjustment" ADD CONSTRAINT "FK_6bdcc15bf8c0230f43893fb367b" FOREIGN KEY ("targetVariationId") REFERENCES "variation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "importation_product" ADD CONSTRAINT "FK_94481838aa4fdee933e806b3cb4" FOREIGN KEY ("generatedById") REFERENCES "adjustment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "importation_product" ADD CONSTRAINT "FK_22cd05ec0702d4edd6e3b40d890" FOREIGN KEY ("importationId") REFERENCES "importation"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "importation_product" ADD CONSTRAINT "FK_4d0801e78547f21d1475edadd81" FOREIGN KEY ("itemId") REFERENCES "item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "importation_product" ADD CONSTRAINT "FK_c83ca0641a188fe278f9ab4ae14" FOREIGN KEY ("variationId") REFERENCES "variation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_allocation" ADD CONSTRAINT "FK_654d57c65cfd091f1a1c7fcbb31" FOREIGN KEY ("mlUserId") REFERENCES "ml_user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_allocation" ADD CONSTRAINT "FK_77d70782a1bb8973f3f1ca9bb30" FOREIGN KEY ("orderItemId") REFERENCES "order_item"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_allocation" ADD CONSTRAINT "FK_a32788fc15e944d3b66b3a1b20c" FOREIGN KEY ("importationProductId") REFERENCES "importation_product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "variation_attribute_options" ADD CONSTRAINT "FK_d29cb7a5f217c9e300c41b5f5d0" FOREIGN KEY ("variationId") REFERENCES "variation"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "variation_attribute_options" ADD CONSTRAINT "FK_0a1f619c76288c49c0a92f974be" FOREIGN KEY ("attributeOptionId") REFERENCES "attribute_option"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "variation_pictures" ADD CONSTRAINT "FK_e952b37a42a238b4adb17d6e353" FOREIGN KEY ("variationId") REFERENCES "variation"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "variation_pictures" ADD CONSTRAINT "FK_c9fee9e9929ee0f136606f49582" FOREIGN KEY ("pictureId") REFERENCES "picture"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "item_pictures" ADD CONSTRAINT "FK_72db30236d484d45d583ba187ab" FOREIGN KEY ("itemId") REFERENCES "item"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "item_pictures" ADD CONSTRAINT "FK_df9bf4e0e22ec4c690c8ecdd6cb" FOREIGN KEY ("pictureId") REFERENCES "picture"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "item_attributes" ADD CONSTRAINT "FK_d2f52db45e62d7dec5e7a9de233" FOREIGN KEY ("itemId") REFERENCES "item"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "item_attributes" ADD CONSTRAINT "FK_19bef966888dbf33b1ce5d63289" FOREIGN KEY ("attributeId") REFERENCES "attribute"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "item_attribute_options" ADD CONSTRAINT "FK_b97c87796847389df04aad724ad" FOREIGN KEY ("itemId") REFERENCES "item"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "item_attribute_options" ADD CONSTRAINT "FK_99d555bf4d5719fd6c0b602cfe0" FOREIGN KEY ("attributeOptionId") REFERENCES "attribute_option"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "item_attribute_options" DROP CONSTRAINT "FK_99d555bf4d5719fd6c0b602cfe0"`);
        await queryRunner.query(`ALTER TABLE "item_attribute_options" DROP CONSTRAINT "FK_b97c87796847389df04aad724ad"`);
        await queryRunner.query(`ALTER TABLE "item_attributes" DROP CONSTRAINT "FK_19bef966888dbf33b1ce5d63289"`);
        await queryRunner.query(`ALTER TABLE "item_attributes" DROP CONSTRAINT "FK_d2f52db45e62d7dec5e7a9de233"`);
        await queryRunner.query(`ALTER TABLE "item_pictures" DROP CONSTRAINT "FK_df9bf4e0e22ec4c690c8ecdd6cb"`);
        await queryRunner.query(`ALTER TABLE "item_pictures" DROP CONSTRAINT "FK_72db30236d484d45d583ba187ab"`);
        await queryRunner.query(`ALTER TABLE "variation_pictures" DROP CONSTRAINT "FK_c9fee9e9929ee0f136606f49582"`);
        await queryRunner.query(`ALTER TABLE "variation_pictures" DROP CONSTRAINT "FK_e952b37a42a238b4adb17d6e353"`);
        await queryRunner.query(`ALTER TABLE "variation_attribute_options" DROP CONSTRAINT "FK_0a1f619c76288c49c0a92f974be"`);
        await queryRunner.query(`ALTER TABLE "variation_attribute_options" DROP CONSTRAINT "FK_d29cb7a5f217c9e300c41b5f5d0"`);
        await queryRunner.query(`ALTER TABLE "sale_allocation" DROP CONSTRAINT "FK_a32788fc15e944d3b66b3a1b20c"`);
        await queryRunner.query(`ALTER TABLE "sale_allocation" DROP CONSTRAINT "FK_77d70782a1bb8973f3f1ca9bb30"`);
        await queryRunner.query(`ALTER TABLE "sale_allocation" DROP CONSTRAINT "FK_654d57c65cfd091f1a1c7fcbb31"`);
        await queryRunner.query(`ALTER TABLE "importation_product" DROP CONSTRAINT "FK_c83ca0641a188fe278f9ab4ae14"`);
        await queryRunner.query(`ALTER TABLE "importation_product" DROP CONSTRAINT "FK_4d0801e78547f21d1475edadd81"`);
        await queryRunner.query(`ALTER TABLE "importation_product" DROP CONSTRAINT "FK_22cd05ec0702d4edd6e3b40d890"`);
        await queryRunner.query(`ALTER TABLE "importation_product" DROP CONSTRAINT "FK_94481838aa4fdee933e806b3cb4"`);
        await queryRunner.query(`ALTER TABLE "adjustment" DROP CONSTRAINT "FK_6bdcc15bf8c0230f43893fb367b"`);
        await queryRunner.query(`ALTER TABLE "adjustment" DROP CONSTRAINT "FK_acf7b6bb7b1893d4aeed2cea6a3"`);
        await queryRunner.query(`ALTER TABLE "adjustment" DROP CONSTRAINT "FK_b860d19aac2598cd33a2d77143a"`);
        await queryRunner.query(`ALTER TABLE "adjustment" DROP CONSTRAINT "FK_ef8cb4525a57f8cd4259d05bd74"`);
        await queryRunner.query(`ALTER TABLE "adjustment" DROP CONSTRAINT "FK_6a441d0c6ebb95ebeee687e7d36"`);
        await queryRunner.query(`ALTER TABLE "importation" DROP CONSTRAINT "FK_3ff2ada593b35db92a146a818a0"`);
        await queryRunner.query(`ALTER TABLE "additional_cost" DROP CONSTRAINT "FK_864571f3c5ef4e22e76b4cba25e"`);
        await queryRunner.query(`ALTER TABLE "additional_cost" DROP CONSTRAINT "FK_07a14ae0d72cf1b421928e32d3e"`);
        await queryRunner.query(`ALTER TABLE "additional_cost_type" DROP CONSTRAINT "FK_541399443980f2e0b65cf41f430"`);
        await queryRunner.query(`ALTER TABLE "sku_equivalence" DROP CONSTRAINT "FK_0c6b1de474ec582a0ba4824fe31"`);
        await queryRunner.query(`ALTER TABLE "shipment" DROP CONSTRAINT "FK_fc82561370970a7d7683eafde04"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_b706d170f54c48fbcd315a9eaf3"`);
        await queryRunner.query(`ALTER TABLE "order" DROP CONSTRAINT "FK_b1f6e7a2d5478991c1e245a4b48"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_e000525ee0adaa7774b12a198ba"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_e03f3ed4dab80a3bf3eca50babc"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_646bf9ece6f45dbe41c203e06e0"`);
        await queryRunner.query(`ALTER TABLE "item" DROP CONSTRAINT "FK_97561f4b60bd81ff26a46c8ad83"`);
        await queryRunner.query(`ALTER TABLE "variation" DROP CONSTRAINT "FK_cff7ea1877724ac753027c2a72a"`);
        await queryRunner.query(`ALTER TABLE "attribute_option" DROP CONSTRAINT "FK_e3c11e0a8635a34ec98815e0f76"`);
        await queryRunner.query(`ALTER TABLE "attribute_option" DROP CONSTRAINT "FK_0f970f7e5632357537ae1230ea8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99d555bf4d5719fd6c0b602cfe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b97c87796847389df04aad724a"`);
        await queryRunner.query(`DROP TABLE "item_attribute_options"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19bef966888dbf33b1ce5d6328"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d2f52db45e62d7dec5e7a9de23"`);
        await queryRunner.query(`DROP TABLE "item_attributes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df9bf4e0e22ec4c690c8ecdd6c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_72db30236d484d45d583ba187a"`);
        await queryRunner.query(`DROP TABLE "item_pictures"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9fee9e9929ee0f136606f4958"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e952b37a42a238b4adb17d6e35"`);
        await queryRunner.query(`DROP TABLE "variation_pictures"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a1f619c76288c49c0a92f974b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d29cb7a5f217c9e300c41b5f5d"`);
        await queryRunner.query(`DROP TABLE "variation_attribute_options"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9617829e678bb9cdb844c86f73"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a32788fc15e944d3b66b3a1b20"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bcab61e68fed299847357b5ed6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77d70782a1bb8973f3f1ca9bb3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_654d57c65cfd091f1a1c7fcbb3"`);
        await queryRunner.query(`DROP TABLE "sale_allocation"`);
        await queryRunner.query(`DROP TYPE "public"."sale_allocation_source_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94481838aa4fdee933e806b3cb"`);
        await queryRunner.query(`DROP TABLE "importation_product"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b860d19aac2598cd33a2d77143"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ef8cb4525a57f8cd4259d05bd7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6a441d0c6ebb95ebeee687e7d3"`);
        await queryRunner.query(`DROP TABLE "adjustment"`);
        await queryRunner.query(`DROP TYPE "public"."adjustment_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ff2ada593b35db92a146a818a"`);
        await queryRunner.query(`DROP TABLE "importation"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_864571f3c5ef4e22e76b4cba25"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_07a14ae0d72cf1b421928e32d3"`);
        await queryRunner.query(`DROP TABLE "additional_cost"`);
        await queryRunner.query(`DROP TYPE "public"."additional_cost_kind_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_541399443980f2e0b65cf41f43"`);
        await queryRunner.query(`DROP TABLE "additional_cost_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0c6b1de474ec582a0ba4824fe3"`);
        await queryRunner.query(`DROP TABLE "sku_equivalence"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1259987790af9fd7eefa8b8cee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc82561370970a7d7683eafde0"`);
        await queryRunner.query(`DROP TABLE "shipment"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b706d170f54c48fbcd315a9eaf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af77cc522fdf7b440f0dc1077a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b24586a2663f7f23e3257be62"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca0148aa1a5929e2a7a1f11f60"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b1f6e7a2d5478991c1e245a4b4"`);
        await queryRunner.query(`DROP TABLE "order"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_628e853a1433b1288c375dfcb9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31d565f22a96ba2d4b2f70f723"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_646bf9ece6f45dbe41c203e06e"`);
        await queryRunner.query(`DROP TABLE "order_item"`);
        await queryRunner.query(`DROP TYPE "public"."order_item_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97561f4b60bd81ff26a46c8ad8"`);
        await queryRunner.query(`DROP TABLE "item"`);
        await queryRunner.query(`DROP TABLE "variation"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b6cba9a12eff2359c1efda994a"`);
        await queryRunner.query(`DROP TABLE "attribute_option"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_80c968aa65a3e2701cc062f60d"`);
        await queryRunner.query(`DROP TABLE "attribute_option_detailed"`);
        await queryRunner.query(`DROP TABLE "attribute"`);
        await queryRunner.query(`DROP TABLE "picture"`);
        await queryRunner.query(`DROP TABLE "ml_user"`);
    }

}
